### PR TITLE
Update Gen 9 Pokemon

### PR DESCRIPTION
**Pull request by AndrewMcQuerry**
# Change Log

* Update Gen 9 Pokemon from PokeMiners
* Update to gradle:7.4.2 (auto-updated by Android Studio)
* Update gradle distributionUrl  (auto-updated by Android Studio)

### CODE REVIEW

**Comment by timoetzold** [comment]
The file "app/src/main/res/values-zh-rCN/pokemons.xml" did not only change on the lines for the new pokemon. That needs to be checked first before accepting this PR.

**Comment by AndrewMcQuerry** [comment]
Good catch.  Not sure what could have caused that.  Is it possible I have an incorrect UTF or language setting?  Also, where do those values come from?  Do they just get copied from names.csv?

**Comment by AndrewMcQuerry** [comment]
Found my mistake.  I had accidentally used the `zh-rTW` list when updating `zh-rCN`.

The latest commit fixes that and now the changes are only to the expected new pokemon.

**Comment by timoetzold** [comment]
How did you do the update? Normally you would run the gradle task ":devMethods:updateDatabase".

**Comment by AndrewMcQuerry** [comment]
Within Android Studio, I ran `ApplicationDatabaseUpdater.java` directly (from within the `devMethods` directory.  This created files in that directory that I then copied into their respective files.

I honestly didn't know exactly how it was done previously.  If there are other things the gradle task does, then maybe this PR should just be closed so that it can be done the correct way.

**Comment by timoetzold** [comment]
already merged. Well the task does the same, but you don't have to do anything manually.

**Pull request merged**
