### PR TITLE
Alolan Pokemon Update

### PR DESCRIPTION
**Pull request by timoetzold**
I fixed the GameMasterParser and updated the resource files, so Alolan Pokemon will work.

### CODE REVIEW

**Comment by jimmywan** [comment]
I haven't worked on this codebase, but the diffs (ignore whitespace) look fairly reasonable to me.
Happy to beta test a build if we get one put together.

**Comment by lramati** [comment]
I'm going to merge this, but I think we need a solution for pumpkaboo and gourgeist. I think each size has different stats, and I'm not sure if we're capable of supporting that right now?

**Comment by timoetzold** [comment]
I did check those as it annoyed me, that the app could not detect other sizes than average. But with this change it is possible!

**Comment by lramati** [comment]
Come to think of it, I don't know if I released a new version when those pokemon were added, maybe its just an old change from when they were actually officially added to the game?

**Comment by timoetzold** [comment]
I guess so. I don't remember either if a new version was released after those were added.

**Comment by lramati** [comment]
Could you just add another commit to bump the version? in app\build.gradle, bump versionCode to 74 and versionName to 5.5.7

**Comment by timoetzold** [comment]
Unfortunately I am on vacation with family, but I can do this tomorrow evening.

**Comment by timoetzold** [comment]
Any update on this?

**Comment by timoetzold** [comment]
This PR now also resolves #7 #8 #9 #12

**Comment by timoetzold** [comment]
Renaming my default branch to main did close this PR, so I reopened it...

**Comment by timoetzold** [comment]
The PR now also resolves #11

**Comment by timoetzold** [comment]
I did some cleanup in the codebase and included commits from @RebelliousUno since my PR replaces #13.
Also I increased the minsdk to 23 and removed the workarounds so this PR also resolves #18.

**Comment by timoetzold** [comment]
I just noticed that at least the online versions need some more work... They currently don't compile as the firebase API changed.

**Comment by timoetzold** [comment]
Implementation is now updated to use FirebaseCrashlytics

**Pull request merged**
